// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA57L80IkWInQC-H23mp_eNKekB0luhzO8',
    appId: '1:605655074301:web:64d93bce6356ad10110594',
    messagingSenderId: '605655074301',
    projectId: 'oua-petcare',
    authDomain: 'oua-petcare.firebaseapp.com',
    storageBucket: 'oua-petcare.appspot.com',
    measurementId: 'G-NJ91ZMBCBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQWcLFBbiSO2UaaG2gdX9stwFLwTBm-Vk',
    appId: '1:605655074301:android:0134f5fc33bfc81a110594',
    messagingSenderId: '605655074301',
    projectId: 'oua-petcare',
    storageBucket: 'oua-petcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTHpz4W-X4wbE5XnhUK6ALxDcVly_plzs',
    appId: '1:605655074301:ios:2c88b9798cc2ebc3110594',
    messagingSenderId: '605655074301',
    projectId: 'oua-petcare',
    storageBucket: 'oua-petcare.appspot.com',
    iosClientId: '605655074301-oojri31flkpn2albepmadp6rofrjp17q.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTHpz4W-X4wbE5XnhUK6ALxDcVly_plzs',
    appId: '1:605655074301:ios:b4e0b5d29eb1f4b0110594',
    messagingSenderId: '605655074301',
    projectId: 'oua-petcare',
    storageBucket: 'oua-petcare.appspot.com',
    iosClientId: '605655074301-2f3junrsf7tmcvr2bqur4survu2mmu6k.apps.googleusercontent.com',
    iosBundleId: 'com.example.petcare.RunnerTests',
  );
}
